# Generated by Django 4.2.2 on 2023-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('idalum', models.BigAutoField(db_column='IdAlum', primary_key=True, serialize=False)),
                ('idc', models.BigIntegerField(blank=True, db_column='IdC', null=True)),
                ('legajonro', models.BigIntegerField(blank=True, db_column='LegajoNro', null=True, verbose_name='Legajo')),
                ('cohorte', models.BigIntegerField(blank=True, db_column='Cohorte', null=True)),
                ('apynom', models.CharField(blank=True, db_column='ApyNom', max_length=255, null=True, verbose_name='Estudiante')),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=255, null=True, verbose_name='DNI')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True, verbose_name='Correo')),
                ('nacfecha', models.DateField(blank=True, db_column='NacFecha', null=True, verbose_name='Nacimiento')),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
    ]
