# Generated by Django 4.2.2 on 2023-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfacu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('iduser', models.BigAutoField(db_column='IdUser', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=255, null=True)),
                ('clave', models.CharField(blank=True, db_column='Clave', max_length=255, null=True)),
                ('perfil', models.CharField(blank=True, db_column='Perfil', max_length=255, null=True)),
                ('perfil2', models.CharField(blank=True, db_column='Perfil2', max_length=255, null=True)),
                ('apeynom', models.CharField(blank=True, db_column='ApeyNom', max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=255, null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=255, null=True)),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('eq1', models.CharField(blank=True, db_column='EQ1', max_length=255, null=True)),
                ('eq2', models.CharField(blank=True, db_column='EQ2', max_length=255, null=True)),
                ('eq3', models.CharField(blank=True, db_column='EQ3', max_length=255, null=True)),
                ('caduca', models.DateField(blank=True, db_column='Caduca', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
